In [1]:
import numpy as np

In [5]:
a = np.arange(10, 1, -1)
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [8]:
b = np.linspace (1, 10, 55)
b

array([ 1.        ,  1.16666667,  1.33333333,  1.5       ,  1.66666667,
        1.83333333,  2.        ,  2.16666667,  2.33333333,  2.5       ,
        2.66666667,  2.83333333,  3.        ,  3.16666667,  3.33333333,
        3.5       ,  3.66666667,  3.83333333,  4.        ,  4.16666667,
        4.33333333,  4.5       ,  4.66666667,  4.83333333,  5.        ,
        5.16666667,  5.33333333,  5.5       ,  5.66666667,  5.83333333,
        6.        ,  6.16666667,  6.33333333,  6.5       ,  6.66666667,
        6.83333333,  7.        ,  7.16666667,  7.33333333,  7.5       ,
        7.66666667,  7.83333333,  8.        ,  8.16666667,  8.33333333,
        8.5       ,  8.66666667,  8.83333333,  9.        ,  9.16666667,
        9.33333333,  9.5       ,  9.66666667,  9.83333333, 10.        ])

In [9]:
c = np.array ([0,1,2,3,4,5])
c

array([0, 1, 2, 3, 4, 5])

In [18]:
np.reshape(c,(3,-1))

array([[0, 1],
       [2, 3],
       [4, 5]])